/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2024-02-13 04:28:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.dashboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboardMgr_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/egov/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/sscm/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1618388108000L));
    _jspx_dependants.put("jar:file:/D:/egov/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/sscm/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<title>Job Korea</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/common_include.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- D3 -->\r\n");
      out.write("<style>\r\n");
      out.write("//\r\n");
      out.write("click-able rows\r\n");
      out.write("\t.clickable-rows {tbody tr td { cursor:pointer;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".el-table__expanded-cell {\r\n");
      out.write("\tcursor: default;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        var pageSizeinf  = 3;\r\n");
      out.write("        var pageBlockSizeinquiry  = 10;\r\n");
      out.write("\r\n");
      out.write("\t\t/* onload 이벤트  */\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\tcomcombo(\"areaCD\", \"areaall\", \"all\", \"2\");   // Group Code, Combo Name, Option(\"all\" : 전체     \"sel\" : 선택 , Select Value )  \r\n");
      out.write("\t\t\tcomcombo(\"JOBCD\", \"joball\", \"all\", \"3\");   // Group Code, Combo Name, Option(\"all\" : 전체     \"sel\" : 선택 , Select Value )  \r\n");
      out.write("\t\t\tcomcombo(\"industryCD\", \"industryall\", \"allindustry\", \"J62\");   // Group Code, Combo Name, Option(\"all\" : 전체     \"sel\" : 선택 , Select Value )  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 공지사항 조회\r\n");
      out.write("\t\t\tfListInf();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//간이차트 조회\r\n");
      out.write("\t\t\t//goChart();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 버튼 이벤트 등록\r\n");
      out.write("\t\t\tfRegisterButtonClickEvent();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t//차트 뿌리러 감\r\n");
      out.write("\t\tfunction goChart(loginID) {\r\n");
      out.write("\t\t\t//alert(\"1\");\r\n");
      out.write("\t\t\t//alert(JSON.stringify(data));\r\n");
      out.write("\t\t\tvar param= {\r\n");
      out.write("\t\t\t\t\tloginID : loginID\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar resultCallback1 = function(data) {\r\n");
      out.write("\t\t//\t alert(\"3\");\r\n");
      out.write("\t\t//\talert(JSON.stringify(data.lec_Name_List));\r\n");
      out.write("\t\t//\talert(JSON.stringify(data.lec_Name_List)) \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfChart (data);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert(\"2\");\r\n");
      out.write("\t\tcallAjax(\"/dashboard/goChart.do\", \"post\", \"json\", true, param, resultCallback1);\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// bar형 chart\r\n");
      out.write("\t\tfunction fChart(data){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t//일단 간단한 값만\r\n");
      out.write("\t\t\tvar cntEngineer = data.cntEngineer;\r\n");
      out.write("\t\t\tvar cntCompany = data.cntCompany;\r\n");
      out.write("\t\t\tvar cntProject = data.cntProject;\r\n");
      out.write("\t\t\t//var cntApplicant = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cntApplicant}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar minChart = new Chart($(\"#minChart\"),{\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttype : 'bar' ,\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\tlabels : ['가입된 엔지니어 수', '가입된 기업 수', '등록된 프로젝트 수', '일별 지원자 수'] ,\r\n");
      out.write("\t\t\t\t\t\tdatasets : [{\r\n");
      out.write("\t\t\t\t\t\t\t\tlabel : '간이 통계' ,\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : [cntEngineer, cntCompany, cntProject] ,\r\n");
      out.write("\t\t\t\t\t\t\t\tborderColor: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'rgba(255, 99, 132, 1)' ,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'rgba(255, 206, 86, 0.2)',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'rgba(54, 162, 235, 0.2)'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t] ,\r\n");
      out.write("\t\t\t\t\t\t\t\tborderWidth : 1\r\n");
      out.write("\t\t\t\t\t\t}]\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/** 버튼 이벤트 등록 */\r\n");
      out.write("\t\tfunction fRegisterButtonClickEvent() {\r\n");
      out.write("\t\t\t$('a[name=btnInfo]').click(function(e) {\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar btnId = $(this).attr('id');\r\n");
      out.write("\t\t\t\tswitch (btnId) {\r\n");
      out.write("\t\t\t\t\tcase 'btnCloseGrpCod' :\r\n");
      out.write("\t\t\t\t\tcase 'btnCloseDtlCod' :\r\n");
      out.write("\t\t\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t/** 공지사항 조회 */\r\n");
      out.write("\t\tfunction fListInf(currentPage) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcurrentPage = currentPage || 1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconsole.log(\"currentPage : \" + currentPage);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar param = {\r\n");
      out.write("\t\t\t\t\t\tcurrentPage : currentPage\r\n");
      out.write("\t\t\t\t\t,\tpageSize : pageSizeinf\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar resultCallback = function(data) {\r\n");
      out.write("\t\t\t\tfListInfResult(data, currentPage);\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//Ajax실행 방식\r\n");
      out.write("\t\t\t//callAjax(\"Url\",type,return,async or sync방식,넘겨준거,값,Callback함수 이름)\r\n");
      out.write("\t\t\t//html로 받을거라 text\r\n");
      out.write("\t\t\tcallAjax(\"/inf/listinf.do\", \"post\", \"text\", true, param, resultCallback);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/** 공지사항 조회 콜백 함수 */\r\n");
      out.write("\t\tfunction fListInfResult(data, currentPage) {\r\n");
      out.write("\t\t\t\t\t//alert(data);\r\n");
      out.write("\t\t\tconsole.log(data);\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 기존 목록 삭제\r\n");
      out.write("\t\t\t$('#listInf').empty();\r\n");
      out.write("\t\t\t$(\"#listInf\").append(data);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 총 개수 추출\r\n");
      out.write("\t\t\tvar totalCntlistInf = $(\"#totcnt\").val();\r\n");
      out.write("\t\t\tvar list = $(\"#selectedInfNo\").val();\r\n");
      out.write("\t\t\t// 페이지 네비게이션 생성\r\n");
      out.write("\t\t\tvar paginationHtml = getPaginationHtml(currentPage, totalCntlistInf, pageSizeinf, pageBlockSizeinquiry, 'fListInf',[list]);\r\n");
      out.write("\t\t\tconsole.log(\"paginationHtml : \" + paginationHtml);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$(\"#listInfPagination\").empty().append( paginationHtml );\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t /*공지사항 상세 조회*/\r\n");
      out.write("\t\t function fNoticeModal(noticeNo) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t var param = {noticeNo : noticeNo};\r\n");
      out.write("\t\t\t var resultCallback2 = function(data){\r\n");
      out.write("\t\t\t\t fdetailResult(data);\r\n");
      out.write("\t\t\t };\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t callAjax(\"/system/detailNotice.do\", \"post\", \"json\", true, param, resultCallback2);\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t /*  공지사항 상세 조회 -> 콜백함수   */\r\n");
      out.write("\t\t function fdetailResult(data){\r\n");
      out.write("\r\n");
      out.write("\t\t\t if(data.resultMsg == \"SUCCESS\"){\r\n");
      out.write("\t\t\t\t //모달 띄우기 \r\n");
      out.write("\t\t\t\t gfModalPop(\"#notice\");\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t// 모달에 정보 넣기 \r\n");
      out.write("\t\t\t\tfrealPopModal(data.result);\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t }else{\r\n");
      out.write("\t\t\t\t alert(data.resultMsg);\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t /* 팝업 _ 초기화 페이지(신규) 혹은 내용뿌리기  */\r\n");
      out.write("\t\t function frealPopModal(object){\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t $(\"#loginId\").val(object.loginId);\r\n");
      out.write("\t\t\t $(\"#loginId\").attr(\"readonly\", true); // 작성자 수정불가 \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t $(\"#write_date\").val(object.noticeRegdate);\r\n");
      out.write("\t\t\t $(\"#write_date\").attr(\"readonly\", true); // 처음 작성된 날짜 수정불가 \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t $(\"#noticeTitle\").val(object.noticeTitle);\r\n");
      out.write("\t\t\t $(\"#noticeTitle\").attr(\"readonly\", true);\r\n");
      out.write("\r\n");
      out.write("\t\t\t $(\"#noticeContent\").val(object.noticeContent);\r\n");
      out.write("\t\t\t $(\"#noticeContent\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t $(\"#noticeNo\").val(object.noticeNo); // 중요한 num 값도 숨겨서 받아온다. \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form id=\"myForm\" action=\"\" method=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"currentPage\" value=\"1\"> <input type=\"hidden\" id=\"selectedInfNo\" value=\"\">\r\n");
      out.write("\t\t<!-- 모달 배경 -->\r\n");
      out.write("\t\t<div id=\"mask\"></div>\r\n");
      out.write("\t\t<div id=\"wrap_area\">\r\n");
      out.write("\t\t\t<h2 class=\"hidden\">컨텐츠 영역</h2>\r\n");
      out.write("\t\t\t<div id=\"container\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"lnb\">\r\n");
      out.write("\t\t\t\t\t\t<!-- lnb 영역 --> ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/lnbMenu.jsp", out, false);
      out.write(" <!--// lnb 영역 -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"contents\">\r\n");
      out.write("\t\t\t\t\t\t<!-- contents -->\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"hidden\">contents 영역</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"Location\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"../dashboard/dashboard.do\" class=\"btn_set home\">메인으로</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"btn_nav bold\">메인</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"../dashboard/dashboard.do\" class=\"btn_set refresh\">새로고침</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"conTitle\" style=\"margin-bottom: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>공지 사항</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fr\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>로그인</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>회원가입</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>마이페이지</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"divComGrpCodList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"5%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"70%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"5%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">작성일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody id=\"listInf\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"paging_area\" id=\"listInfPagination\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 프로젝트 조회 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"selectProject\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\" cellpadding=\"5\" cellspacing=\"0\" border=\"1\" align=\"left\" style=\"border-collapse: collapse; border: 10px #50bcdf;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr style=\"border: 10px; border-color: blue\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"20\" height=\"25\" style=\"font-size: 120%\">&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"220\" height=\"25\" style=\"font-size: 150%; font-weight: bold;\">프로젝트 조회</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"30\" height=\"25\" style=\"font-size: 100%\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"40\" height=\"25\" style=\"font-size: 100%\">지역&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><select id=\"areaall\" name=\"areaall\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"30\" height=\"25\" style=\"font-size: 100%\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"40\" height=\"25\" style=\"font-size: 100%\">직무&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><select id=\"joball\" name=\"joball\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"30\" height=\"25\" style=\"font-size: 100%\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"40\" height=\"25\" style=\"font-size: 100%\">산업&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><select id=\"industryall\" name=\"industryall\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"180\" height=\"25\" style=\"font-size: 120%\">&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"100\" height=\"60\" style=\"font-size: 120%\"><a href=\"\" class=\"btnType blue\" id=\"searchBtn\" name=\"btn\"><span>검 색</span></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"20\" height=\"25\" style=\"font-size: 120%\">&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"divListProject\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"8%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">회사명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">지역</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">직무</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">산업</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">작성일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">모집마감일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">작성 회사</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody id=\"listProject\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"12\">조건에 맞는 프로젝트 목록이 조회됩니다.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"paging_area\" id=\"listProjectPagination\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 통계 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"stat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\" cellpadding=\"5\" cellspacing=\"0\" border=\"1\" align=\"left\" style=\"border-collapse: collapse; border: 10px #50bcdf;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr style=\"border: 10px; border-color: blue\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"20\" height=\"25\" style=\"font-size: 120%\">&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"950\" height=\"25\" style=\"font-size: 150%; font-weight: bold;\">간이 통계</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"30\" height=\"25\" style=\"font-size: 100%\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"statView\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas id=\"minChart\" style=\"height: 30vh;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> <!--// content -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"infModal\" class=\"layerPop layerType2\" style=\"width: 900px;\">\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<strong>1:1문의</strong>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t<dd class=\"content\">\r\n");
      out.write("\t\t\t\t\t<!-- s : 여기에 내용입력 -->\r\n");
      out.write("\t\t\t\t\t<table class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"120px\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"120px\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" class=\"inputTxt p100\" name=\"grp_cod_eplti\" id=\"inf_title\" maxlength=\"100\" readonly /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><textarea class=\"inputTxt p100\" style=\"height: 200px; word-break: break-all;\" name=\"grp_cod_eplti\" id=\"inf_content\" readonly></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">첨부 파일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"filedown\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn_areaC mt30\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" class=\"btnType gray\" id=\"btnCloseGrpCod\" name=\"btnInfo\"><span>취소</span></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 모달팝업 -->\r\n");
      out.write("\t\t<div id=\"notice\" class=\"layerPop layerType2\" style=\"width: 600px;\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"noticeNo\" name=\"noticeNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noticeNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t<!-- 수정시 필요한 num 값을 넘김  -->\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<strong>공지사항</strong>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t<dd class=\"content\">\r\n");
      out.write("\t\t\t\t\t<!-- s : 여기에 내용입력 -->\r\n");
      out.write("\t\t\t\t\t<table class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">작성자 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\" name=\"loginId\" id=\"loginId\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <th scope=\"row\">작성일<span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\" name=\"write_date\" id=\"write_date\" /></td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">제목 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" class=\"inputTxt p100\" name=\"noticeTitle\" id=\"noticeTitle\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><textarea class=\"inputTxt p100\" name=\"noticeContent\" id=\"noticeContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<!-- e : 여기에 내용입력 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"btn_areaC mt30\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" class=\"btnType gray\" id=\"btnClose\" name=\"btn\"><span>닫기</span></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 꾸밀수 있는 거 2 -->\r\n");
      out.write("\t\t<!--          <div>\r\n");
      out.write("\t                        <template id=\"searcharea2\">\r\n");
      out.write("\t                             <div class=\"input-group date\" style=\"width:150px;\">\r\n");
      out.write("\t                                      <input id=\"indate\" name=\"indate\" type=\"text\" class=\"form-control\" v-model=\"date\" />\r\n");
      out.write("\t                                     <span class=\"input-group-addon\">asdf<i class=\"fa fa-calendar\"></i></span>\r\n");
      out.write("\t                            </div>                            \r\n");
      out.write("\t                       </template>\r\n");
      out.write("                       </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t꾸밀수 있는 거 3\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<template id=\"searcharea2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group date\" style=\"width: 150px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"indate\" name=\"indate\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" v-model=\"date\" /> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\">iiiii<i class=\"fa fa-calendar\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</template>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t -->\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/view/dashboard/dashboardMgr.jsp(234,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userType eq null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<span>로그인</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<span>일반 회원가입</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<span>기업 회원가입</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/view/dashboard/dashboardMgr.jsp(239,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userType eq 'A'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<span>로그아웃</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/view/dashboard/dashboardMgr.jsp(242,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userType eq 'B'} or ${sessionScope.userType eq 'C'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<span>로그아웃</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<span>마이페이지</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
